image: node:latest

stages:
  - build
  - test
  - deploy

cache:
    paths:
    - ./node_modules

build:
  script:
    - npm install
    - ./node_modules/@angular/cli/bin/ng build
  artifacts:
    paths:
      - dist/

test:
  script:
    - echo "Alex"
    #- ./node_modules/@angular/cli/bin/ng lint
    #- ./node_modules/@angular/cli/bin/ng test --single-run=true --browsers PhantomJS --watch=false

pages:
  stage: deploy
  script:
  - mv doc public
  artifacts:
    paths:
    - public
  only:
  - master
